destination:    ./_site
lsi:            false
pygments:       true
pygments_cache: ./_cache
markdown:       maruku
permalink:      pretty
extensions:     true
exclude:        ['Rakefile', 'README.markdown', 'TODO.markdown', '_drafts']